Initial kafka integration tests
stackabletech/kafka-operator-integration-tests pull request #1
Opened 2021-08-30 09:01 UTC by maltesander

- Create a cluster
- Scale a cluster up and down
- Check if container ports and monitoring is set up correctly

2021-08-30 14:25 UTC, lfrancke requested changes

2021-08-30 14:25 UTC, lfrancke commented on .github/workflows/rust.yml
> +  clippy:
Could you look at e.g. operator-rs and include rustdoc here?

2021-08-30 14:25 UTC, lfrancke commented on .github/workflows/rust.yml
> +      - uses: actions-rs/audit-check@v1.2.0
```suggestion
      - uses: actions-rs/audit-check@v1.2.6
```

2021-08-30 14:25 UTC, lfrancke commented on Cargo.toml
> +name = "kafka-operator-integration-tests"
Could you include a single line here

`repository = "https://github.com/stackabletech/kafka-operator-integration-tests"`

2021-08-30 14:25 UTC, lfrancke commented on Cargo.toml
> +version = "0.1.0-nightly"
```suggestion
version = "0.1.0"
```

I talked to @siegfriedweber  and we decided to skip the nightly tag for integration tests

2021-08-30 15:58 UTC, maltesander commented on .github/workflows/rust.yml
> +      - uses: actions-rs/audit-check@v1.2.0
There is no 1.2.6? I used it without checking and did not work. Ill go back to [1.2.0](https://github.com/actions-rs/audit-check/releases).

2021-09-20 15:09 UTC, razvan approved these changes
lgtm

2021-09-20 16:09 UTC, backstreetkiwi commented
Hi @maltesander, I tested this with Jenkins and it failed. Maybe I didn't fulfill all prerequisites?

Logs: https://ci.stackable.tech/job/Kafka%20Operator%20Integration%20Tests/1/artifact/target/test_output.log
Cluster setup: https://ci.stackable.tech/job/Kafka%20Operator%20Integration%20Tests/1/artifact/target/stackable-versions.txt

2021-09-21 08:58 UTC, backstreetkiwi commented
UPDATE: I included a ZooKeeper service to the test cluster definition, now it works: https://ci.stackable.tech/job/Kafka%20Operator%20Integration%20Tests/3/

2021-09-21 08:58 UTC, backstreetkiwi approved these changes
Black-box-test successful: https://ci.stackable.tech/job/Kafka%20Operator%20Integration%20Tests/3/

2021-09-21 09:07 UTC, lfrancke approved these changes
Only a single comment but looks good and can be merged like this

2021-09-21 09:07 UTC, lfrancke commented on Cargo.toml
> +integration-test-commons = { git = "https://github.com/stackabletech/integration-test-commons.git", branch = "main" }
Can we move to a released tag here?

2021-09-21 09:25 UTC, lfrancke approved these changes

2021-09-21 09:29 UTC, merged